// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tpyycvuudddsgvsjknvi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRweXljdnV1ZGRkc2d2c2prbnZpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyNjQ4MTQsImV4cCI6MjA2NDg0MDgxNH0.XPvE49-t2nIVlSX5GtQZxmOeRlWkSdqiMfGT5zI5rYU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);